apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: medlas/jenkins-flask
        name: flaskdemo
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: NodePort
  selector:
    app: flaskdemo
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007
