apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
  labels:
    app: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: medlas/jenkins-flask:{{ .Values.image.tag }}
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      # Add this annotation to force Kubernetes to detect changes
      annotations:
        kubernetes.io/change-cause: "Build number {{ .Values.buildNumber }}"

---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  type: NodePort
  selector:
    app: flaskdemo
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007
